---
include:
  default:
    - profile::application::openssl

# Disable haproxy and rsyslog in vagrant (modules not in Puppetfile)
profile::highavailability::loadbalancing::haproxy::manage_haproxy: false
profile::highavailability::loadbalancing::haproxy::manage_firewall: false
profile::logging::rsyslog::client::manage_rsyslog: false

profile::application::openssl::manage_ca_cert: true

object__backend__names:    ['%{::location}-rgw-01']
object__backend__ips:      ["%{hiera('netcfg_trp_netpart')}.84"]

frontend_star_ssl_pem:    "star.%{hiera('domain_frontend')}.pem"

profile::application::openssl::certs:
  "star.%{hiera('domain_frontend')}":
    cn:     "*.%{hiera('domain_frontend')}"
    altnames:
      - "status.%{hiera('domain_frontend')}"
      - "access.%{hiera('domain_frontend')}"
      - "report.%{hiera('domain_frontend')}"
      - "api.%{hiera('domain_frontend')}"
    concat: true
  "star.api.%{hiera('domain_public')}":
    cn:     "*.api.%{hiera('domain_public')}"
    altnames:
      - "*.api.%{hiera('domain_public')}"
    concat: true
  "console.%{hiera('domain_public')}":
    cn:     "console.%{hiera('domain_public')}"
    concat: true
